### ISSUE TITLE
Prepare Lisk Core v4.0.0 for rc

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-core#641]
### Description

The purpose of this epic is to prepare the Lisk Core v4.0.0-rc.0 release

### Tasks

- [x] LiskHQ/lisk-core#727
- [x] LiskHQ/lisk-core#778
- [x]  LiskHQ/lisk-core#780
- [x] LiskHQ/lisk-core#776
- [x] LiskHQ/lisk-core#772
- [x] LiskHQ/lisk-core#785
- [x] LiskHQ/lisk-core#793
- [x] LiskHQ/lisk-core#791
- [x] LiskHQ/lisk-core#798
- [x] LiskHQ/lisk-core#800
- [x] LiskHQ/lisk-core#804
- [x] LiskHQ/lisk-core#803
- [x] LiskHQ/lisk-core#782
- [x] LiskHQ/lisk-core#801
- [x] LiskHQ/lisk-core#807
- [x] LiskHQ/lisk-core#812
- [x] LiskHQ/lisk-core#786
- [x] LiskHQ/lisk-core#808
- [x] LiskHQ/lisk-core#817
- [x] LiskHQ/lisk-core#818
- [x] LiskHQ/lisk-core#828
- [x] LiskHQ/lisk-core#825
- [x] LiskHQ/lisk-core#792
- [x] LiskHQ/lisk-core#815
- [x] LiskHQ/lisk-core#821
